# Generated by Django 2.1.3 on 2018-11-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza2go', '0002_auto_20181122_1225'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pizzasize',
            unique_together={('name', 'pizza')},
        ),
    ]
