# Generated by Django 2.1.3 on 2018-11-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza2go', '0004_auto_20181128_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usershoppingcart',
            old_name='size',
            new_name='pizza_size',
        ),
    ]
