# Generated by Django 2.1.3 on 2018-12-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza2go', '0007_auto_20181212_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_finished',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_finished',
            field=models.TimeField(blank=True),
        ),
    ]
