# Generated by Django 2.1.3 on 2018-12-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza2go', '0008_auto_20181219_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_finished',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_finished',
            field=models.TimeField(null=True),
        ),
    ]
